name: build

on:
  push:
    branches:
    - master
jobs:
   build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tests/tests_from_scratch
    steps:
      - uses: actions/checkout@v2
      - name: make
        run: make
        
