name: valgrind

on:
  push:
    branches:
    - main
jobs:
   test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tests/tests_from_scratch
    steps:
      - uses: actions/checkout@v2
      - name: Install valgrind
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind
      - name: Run valgrind
        run: make leakfull
